spec:
  template:
    spec:
      containers:
        -
          env:
          - name: AMQP_SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: spring-boot-camel-amq-config
                key: service.host
          - name: AMQP_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: spring-boot-camel-amq-config
                key: service.port
          - name: AMQP_PARAMETERS
            value: transport.trustAll=true&transport.verifyHost=false&amqp.idleTimeout=120000
          - name: AMQP_USERNAME
            valueFrom:
              configMapKeyRef:
                name: spring-boot-camel-amq-config
                key: service.username
          - name: AMQP_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: spring-boot-camel-amq-config
                key: service.password
          - name: AMQP_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: spring-boot-camel-amq-config
                key: service.protocol